name: Node打卡任务

on:
  workflow_dispatch: # 允许手动点击运行
  schedule:
    - cron: '30 22 * * *' # 每天自动运行

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取你的代码
        uses: actions/checkout@v4

      - name: 准备 Node.js 20 环境
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 后台启动官方 API 服务
        run: |
          # 使用 npx 直接拉取并运行 NPM 镜像库里的最新版网易云 API
          # 加 & 符号让它在后台静默运行
          npx -y NeteaseCloudMusicApi &
          # 稍微等 8 秒钟，确保 API 服务在本地 3000 端口完全启动
          sleep 8 

      - name: 运行你的 JS 刷歌脚本
        env:
          MUSIC_U: ${{ secrets.MUSIC_U }}
        run: |
          node checkin.js
